# Generated by Django 4.1.3 on 2023-01-11 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mutations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aa_original', models.CharField(max_length=1)),
                ('aa_pos', models.IntegerField()),
                ('aa_mutated', models.CharField(max_length=1)),
                ('hydrophobicity', models.BooleanField()),
                ('volume', models.BooleanField()),
                ('chemical_characteristics', models.BooleanField()),
                ('aa_changes', models.CharField(max_length=17)),
                ('region', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sequences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Run_Identifier', models.CharField(max_length=100)),
                ('Sequence_Number', models.IntegerField()),
                ('Sequence_ID', models.CharField(max_length=100)),
                ('V_DOMAIN_Functionality', models.CharField(max_length=100)),
                ('V_GENE_and_allele', models.TextField()),
            ],
            options={
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='Mutations_bases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_original', models.CharField(max_length=1)),
                ('base_pos', models.IntegerField()),
                ('base_mutated', models.CharField(max_length=1)),
                ('aa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PinkStrawberry.mutations')),
            ],
        ),
        migrations.AddField(
            model_name='mutations',
            name='sequence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PinkStrawberry.sequences'),
        ),
    ]
