# Generated by Django 4.1.3 on 2023-01-25 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PinkStrawberry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequences',
            name='IMGT_sequence',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='sequences',
            name='submitted_sequence',
            field=models.TextField(default=''),
        ),
    ]
