# Generated by Django 4.1.3 on 2023-01-27 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PinkStrawberry', '0003_predictions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mutations',
            options={'get_latest_by': 'id'},
        ),
    ]
