# Generated by Django 4.1.3 on 2023-01-31 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PinkStrawberry', '0004_alter_mutations_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunIdentifiers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'get_latest_by': 'id',
            },
        ),
        migrations.AlterField(
            model_name='sequences',
            name='Run_Identifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PinkStrawberry.runidentifiers'),
        ),
    ]
