# Generated by Django 4.1.3 on 2023-01-31 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PinkStrawberry', '0005_runidentifiers_alter_sequences_run_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutations',
            name='aa_changes',
            field=models.CharField(max_length=18),
        ),
    ]
