# Generated by Django 4.1.3 on 2023-01-31 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PinkStrawberry', '0006_alter_mutations_aa_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='runidentifiers',
            name='description',
            field=models.TextField(default='None'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='runidentifiers',
            name='run_name',
            field=models.TextField(default='None'),
            preserve_default=False,
        ),
    ]
