# Generated by Django 4.1.3 on 2023-01-31 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PinkStrawberry', '0007_runidentifiers_description_runidentifiers_run_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequences',
            name='submitted_sequence_translated',
            field=models.TextField(default='None'),
            preserve_default=False,
        ),
    ]
