# Generated by Django 4.1.3 on 2023-02-10 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PinkStrawberry', '0009_alter_sequences_imgt_sequence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutations',
            name='sequence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='PinkStrawberry.sequences'),
        ),
        migrations.AlterField(
            model_name='mutations_bases',
            name='aa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutations', to='PinkStrawberry.mutations'),
        ),
        migrations.AlterField(
            model_name='predictions',
            name='sequence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='PinkStrawberry.sequences'),
        ),
        migrations.AlterField(
            model_name='sequences',
            name='Run_Identifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='PinkStrawberry.runidentifiers'),
        ),
    ]
