# Generated by Django 4.1.3 on 2023-02-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PinkStrawberry', '0011_run_identifier_sequence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run_identifier',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='run_identifier',
            name='run_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='summary',
            name='V_REGION_identity_nt_with_insdel_events',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='summary',
            name='V_REGION_identity_percent_with_insdel_events',
            field=models.FloatField(null=True),
        ),
    ]
