# Generated by Django 4.1.3 on 2023-02-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PinkStrawberry', '0013_alter_aa_sequences_cdr1_imgt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nt_sequences',
            name='Pfiveprime_J_end',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nt_sequences',
            name='Pfiveprime_J_start',
            field=models.IntegerField(null=True),
        ),
    ]
