# Generated by Django 4.1.3 on 2023-02-20 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PinkStrawberry', '0015_sequence_translated_sequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Glycosite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sequence', models.CharField(max_length=4)),
                ('Start', models.IntegerField()),
                ('Stop', models.IntegerField()),
                ('Sequence_Identifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Glycosite', to='PinkStrawberry.sequence')),
            ],
            options={
                'get_latest_by': 'id',
            },
        ),
    ]
