# Generated by Django 4.1.3 on 2023-02-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PinkStrawberry', '0016_glycosite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Germline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Accesion_number', models.TextField(null=True)),
                ('Gene_and_allele', models.TextField(null=True)),
                ('Species', models.TextField(null=True)),
                ('Functionality', models.TextField(null=True)),
                ('Labels', models.TextField(null=True)),
                ('Accesion_start_end', models.TextField(null=True)),
                ('Accesion_nucleotide_nb', models.TextField(null=True)),
                ('Codon_start', models.TextField(null=True)),
                ('Fiveprime_changed', models.TextField(null=True)),
                ('Threeprime_changed', models.TextField(null=True)),
                ('Sequencing_changed', models.TextField(null=True)),
                ('AA_nb', models.TextField(null=True)),
                ('Length', models.TextField(null=True)),
                ('Partial', models.TextField(null=True)),
                ('Reverse_complementary', models.TextField(null=True)),
                ('Sequence', models.TextField(null=True)),
            ],
        ),
    ]
