# Generated by Django 4.1.3 on 2023-02-21 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PinkStrawberry', '0017_germline'),
    ]

    operations = [
        migrations.CreateModel(
            name='IMGT_Gene_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release', models.TextField()),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'get_latest_by': 'id',
            },
        ),
        migrations.AddField(
            model_name='germline',
            name='IMGT_Gene_DB',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Germline', to='PinkStrawberry.imgt_gene_db'),
            preserve_default=False,
        ),
    ]
