# Generated by Django 4.1.3 on 2023-02-23 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PinkStrawberry', '0018_imgt_gene_db_germline_imgt_gene_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Identifier', models.TextField()),
                ('Comment', models.TextField(null=True)),
            ],
            options={
                'get_latest_by': 'id',
            },
        ),
        migrations.AddField(
            model_name='sequence',
            name='Nt_Constant',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='sequence',
            name='Nt_Leading',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='BCR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Identifier', models.TextField()),
                ('Mass', models.FloatField(null=True)),
                ('Run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BCR', to='PinkStrawberry.run_identifier')),
            ],
        ),
        migrations.AddField(
            model_name='sequence',
            name='BCR',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Sequence', to='PinkStrawberry.bcr'),
        ),
    ]
