# Generated by Django 4.1.3 on 2023-02-23 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PinkStrawberry', '0019_patient_sequence_nt_constant_sequence_nt_leading_bcr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='Patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Sequence', to='PinkStrawberry.patient'),
        ),
    ]
