# Generated by Django 4.1.3 on 2023-03-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PinkStrawberry', '0021_rename_translated_sequence_sequence_aa_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='Type',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
