# Generated by Django 4.1.3 on 2023-03-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PinkStrawberry', '0022_sequence_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='Comment',
            field=models.TextField(null=True),
        ),
    ]
