# Generated by Django 4.1.3 on 2023-03-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PinkStrawberry', '0023_sequence_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='AA_Constant',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='sequence',
            name='AA_Leading',
            field=models.TextField(null=True),
        ),
    ]
