# Generated by Django 4.1.3 on 2023-03-03 15:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PinkStrawberry', '0024_sequence_aa_constant_sequence_aa_leading'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'get_latest_by': 'created_at'},
        ),
        migrations.AddField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='Identifier',
            field=models.TextField(unique=True),
        ),
        migrations.AddField(
            model_name='sequence',
            name='Subtype',
            field=models.ManyToManyField(to='PinkStrawberry.subtype'),
        ),
    ]
