# Generated by Django 4.1.3 on 2023-03-03 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PinkStrawberry', '0025_subtype_alter_patient_options_patient_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'get_latest_by': 'id'},
        ),
        migrations.RemoveField(
            model_name='patient',
            name='created_at',
        ),
    ]
