# Generated by Django 4.1.3 on 2023-03-15 22:05

import PinkStrawberry.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PinkStrawberry', '0027_sequence_d_germline_sequence_j_germline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VQuest_Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_name', models.TextField()),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Summary', models.FileField(upload_to=PinkStrawberry.models._vquest_path)),
                ('IMGT_gapped_nt_sequences', models.FileField(upload_to=PinkStrawberry.models._vquest_path)),
                ('Nt_sequences', models.FileField(upload_to=PinkStrawberry.models._vquest_path)),
                ('IMGT_gapped_AA_sequences', models.FileField(upload_to=PinkStrawberry.models._vquest_path)),
                ('AA_sequences', models.FileField(upload_to=PinkStrawberry.models._vquest_path)),
                ('Junction', models.FileField(upload_to=PinkStrawberry.models._vquest_path)),
                ('V_REGION_mutation_and_AA_change_table', models.FileField(upload_to=PinkStrawberry.models._vquest_path)),
                ('V_REGION_nt_mutation_statistics', models.FileField(upload_to=PinkStrawberry.models._vquest_path)),
                ('V_REGION_AA_change_statistics', models.FileField(upload_to=PinkStrawberry.models._vquest_path)),
                ('V_REGION_mutation_hotspots', models.FileField(upload_to=PinkStrawberry.models._vquest_path)),
                ('Parameters', models.FileField(upload_to=PinkStrawberry.models._vquest_path)),
            ],
            options={
                'get_latest_by': 'id',
            },
        ),
    ]
