# Generated by Django 4.1.3 on 2023-03-17 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PinkStrawberry', '0028_vquest_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aa_sequences',
            name='Sequence_Identifier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='AA_sequences', to='PinkStrawberry.sequence'),
        ),
        migrations.AlterField(
            model_name='imgt_gapped_aa_sequences',
            name='Sequence_Identifier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='IMGT_gapped_AA_sequences', to='PinkStrawberry.sequence'),
        ),
        migrations.AlterField(
            model_name='imgt_gapped_nt_sequences',
            name='Sequence_Identifier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='IMGT_gapped_nt_sequences', to='PinkStrawberry.sequence'),
        ),
        migrations.AlterField(
            model_name='junction',
            name='Sequence_Identifier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Junction', to='PinkStrawberry.sequence'),
        ),
        migrations.AlterField(
            model_name='nt_sequences',
            name='Sequence_Identifier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Nt_sequences', to='PinkStrawberry.sequence'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='Sequence_Identifier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Summary', to='PinkStrawberry.sequence'),
        ),
        migrations.AlterField(
            model_name='v_region_aa_change_statistics',
            name='Sequence_Identifier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='V_REGION_AA_change_statistics', to='PinkStrawberry.sequence'),
        ),
        migrations.AlterField(
            model_name='v_region_mutation_and_aa_change_table',
            name='Sequence_Identifier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='V_REGION_mutation_and_AA_change_table', to='PinkStrawberry.sequence'),
        ),
        migrations.AlterField(
            model_name='v_region_mutation_hotspots',
            name='Sequence_Identifier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='V_REGION_mutation_hotspots', to='PinkStrawberry.sequence'),
        ),
        migrations.AlterField(
            model_name='v_region_nt_mutation_statistics',
            name='Sequence_Identifier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='V_REGION_nt_mutation_statistics', to='PinkStrawberry.sequence'),
        ),
    ]
