# Generated by Django 4.1.3 on 2023-03-17 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PinkStrawberry', '0030_project_rename_run_name_vquest_run_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vquest_run',
            name='Comment',
            field=models.TextField(null=True),
        ),
    ]
