# Generated by Django 4.1.3 on 2023-03-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PinkStrawberry', '0032_alter_vquest_run_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='Nt_Sequence',
            field=models.TextField(null=True),
        ),
    ]
