# Generated by Django 4.1.3 on 2023-03-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PinkStrawberry', '0033_sequence_nt_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='glycosite',
            name='Region',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
