# Generated by Django 4.1.3 on 2023-03-28 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PinkStrawberry', '0034_glycosite_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='AA_change',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aa_original', models.CharField(max_length=1)),
                ('aa_pos', models.IntegerField()),
                ('aa_mutated', models.CharField(max_length=1)),
                ('hydrophobicity', models.BooleanField()),
                ('volume', models.BooleanField()),
                ('chemical_characteristics', models.BooleanField()),
                ('similarity', models.CharField(max_length=18)),
                ('region', models.CharField(max_length=10)),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AA_change', to='PinkStrawberry.sequence')),
            ],
            options={
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='Nt_mutation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nt_original', models.CharField(max_length=1)),
                ('nt_pos', models.IntegerField()),
                ('nt_mutated', models.CharField(max_length=1)),
                ('aa_change', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Nt_mutation', to='PinkStrawberry.aa_change')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Nt_mutation', to='PinkStrawberry.sequence')),
            ],
        ),
    ]
