# Generated by Django 4.1.3 on 2023-03-28 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PinkStrawberry', '0035_aa_change_nt_mutation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aa_change',
            old_name='aa_mutated',
            new_name='aa_changed',
        ),
    ]
