# Generated by Django 4.1.3 on 2023-03-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PinkStrawberry', '0036_rename_aa_mutated_aa_change_aa_changed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aa_change',
            name='similarity',
            field=models.IntegerField(choices=[(0, 'Very dissimilar'), (1, 'Dissimilar'), (2, 'Similar'), (3, 'Very similar'), (4, 'Identical')]),
        ),
    ]
