# Generated by Django 4.1.3 on 2023-03-31 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PinkStrawberry', '0037_alter_aa_change_similarity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='germline',
            old_name='Sequence',
            new_name='AA_Sequence',
        ),
        migrations.AddField(
            model_name='germline',
            name='Nt_Sequence',
            field=models.TextField(null=True),
        ),
    ]
