# Generated by Django 4.1.3 on 2023-03-31 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PinkStrawberry', '0038_rename_sequence_germline_aa_sequence_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mutations_bases',
            name='aa',
        ),
        migrations.RemoveField(
            model_name='predictions',
            name='sequence',
        ),
        migrations.RemoveField(
            model_name='sequences',
            name='Run_Identifier',
        ),
        migrations.DeleteModel(
            name='Mutations',
        ),
        migrations.DeleteModel(
            name='Mutations_bases',
        ),
        migrations.DeleteModel(
            name='Predictions',
        ),
        migrations.DeleteModel(
            name='RunIdentifiers',
        ),
        migrations.DeleteModel(
            name='Sequences',
        ),
    ]
