# Generated by Django 4.1.3 on 2023-04-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PinkStrawberry', '0040_alter_junction_accepted_d_gene_nb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nt_sequences',
            name='fiveprime_J_REGION',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='nt_sequences',
            name='fiveprime_J_REGION_end',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nt_sequences',
            name='fiveprime_J_REGION_start',
            field=models.IntegerField(null=True),
        ),
    ]
