# Generated by Django 4.1.3 on 2023-04-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PinkStrawberry', '0041_alter_nt_sequences_fiveprime_j_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='junction',
            name='JUNCTION',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='junction',
            name='JUNCTION_frame',
            field=models.TextField(null=True),
        ),
    ]
