# Generated by Django 4.1.3 on 2023-05-01 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PinkStrawberry', '0042_alter_junction_junction_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AA_change',
            new_name='IMGT_AA_change',
        ),
        migrations.RenameModel(
            old_name='Nt_mutation',
            new_name='IMGT_Nt_mutation',
        ),
    ]
