# Generated by Django 4.1.3 on 2023-05-01 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PinkStrawberry', '0043_rename_aa_change_imgt_aa_change_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgt_aa_change',
            name='sequence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='IMGT_AA_change', to='PinkStrawberry.sequence'),
        ),
        migrations.AlterField(
            model_name='imgt_nt_mutation',
            name='aa_change',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='IMGT_Nt_mutation', to='PinkStrawberry.imgt_aa_change'),
        ),
        migrations.AlterField(
            model_name='imgt_nt_mutation',
            name='sequence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='IMGT_Nt_mutation', to='PinkStrawberry.sequence'),
        ),
    ]
