# Generated by Django 4.1.3 on 2023-05-01 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PinkStrawberry', '0045_aa_change_nt_mutation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aa_change',
            old_name='nt_mutated',
            new_name='mutated',
        ),
        migrations.RenameField(
            model_name='aa_change',
            old_name='nt_original',
            new_name='original',
        ),
        migrations.RenameField(
            model_name='aa_change',
            old_name='nt_pos',
            new_name='pos',
        ),
    ]
