# Generated by Django 4.1.3 on 2023-08-01 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PinkStrawberry', '0049_peptide_comparison'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ms_peptide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peptide', models.TextField()),
                ('start', models.IntegerField()),
                ('stop', models.IntegerField()),
                ('confidence', models.TextField()),
                ('allele', models.TextField()),
                ('quality_qval', models.FloatField()),
                ('Comment', models.TextField(null=True)),
                ('sequence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Ms_peptide', to='PinkStrawberry.sequence')),
            ],
        ),
    ]
