# Generated by Django 4.1.3 on 2023-08-06 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PinkStrawberry', '0052_ms_peptide__sheet_sequence_alter_ms_peptide_allele_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ms_peptide',
            old_name='_sheet_sequence',
            new_name='sheet_sequence',
        ),
    ]
