# Generated by Django 4.1.3 on 2023-08-07 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PinkStrawberry', '0053_rename__sheet_sequence_ms_peptide_sheet_sequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Predicted_Found',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.IntegerField(choices=[(0, 'Low'), (1, 'Medium'), (2, 'High')])),
                ('found', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairing', to='PinkStrawberry.ms_peptide')),
                ('predicted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairing', to='PinkStrawberry.prediction')),
                ('sequence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predicted_found', to='PinkStrawberry.sequence')),
            ],
        ),
    ]
