# Generated by Django 4.1.3 on 2023-08-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PinkStrawberry', '0055_prediction_germline'),
    ]

    operations = [
        migrations.AddField(
            model_name='ms_peptide',
            name='possible_allele',
            field=models.TextField(null=True),
        ),
    ]
