# Generated by Django 4.1.3 on 2023-08-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PinkStrawberry', '0057_mhc_allele'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mhc_allele',
            name='id',
        ),
        migrations.AlterField(
            model_name='mhc_allele',
            name='name',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
