# Generated by Django 4.1.3 on 2023-08-08 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PinkStrawberry', '0058_remove_mhc_allele_id_alter_mhc_allele_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ms_peptide',
            name='allele',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Ms_peptides', to='PinkStrawberry.mhc_allele'),
        ),
        migrations.AlterField(
            model_name='ms_peptide',
            name='possible_allele',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Ms_peptides_possible', to='PinkStrawberry.mhc_allele'),
        ),
        migrations.AlterField(
            model_name='peptide_comparison',
            name='allele',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Pred_peptides_comparison', to='PinkStrawberry.mhc_allele'),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='allele',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Pred_peptides', to='PinkStrawberry.mhc_allele'),
        ),
    ]
