# Generated by Django 4.1.3 on 2023-08-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PinkStrawberry', '0059_alter_ms_peptide_allele_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ms_peptide',
            name='possible_allele',
        ),
        migrations.AddField(
            model_name='ms_peptide',
            name='possible_allele',
            field=models.ManyToManyField(related_name='Ms_peptides_possible', to='PinkStrawberry.mhc_allele'),
        ),
    ]
