# Generated by Django 4.1.3 on 2023-08-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PinkStrawberry', '0060_remove_ms_peptide_possible_allele_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predicted_found',
            name='quality',
            field=models.IntegerField(choices=[(0, 'Low'), (1, 'Medium'), (2, 'High')], null=True),
        ),
    ]
