# Generated by Django 4.1.3 on 2023-08-15 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PinkStrawberry', '0064_prediction_sequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='alignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('position', models.IntegerField()),
                ('sequence', models.TextField()),
                ('linked_sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alignment', to='PinkStrawberry.sequence')),
            ],
        ),
    ]
