# Generated by Django 4.1.3 on 2023-08-15 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PinkStrawberry', '0065_alignment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aa_change',
            old_name='pos',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='nt_mutation',
            old_name='mutated',
            new_name='changed',
        ),
        migrations.RenameField(
            model_name='nt_mutation',
            old_name='pos',
            new_name='position',
        ),
    ]
