# Generated by Django 4.1.3 on 2023-08-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PinkStrawberry', '0066_rename_pos_aa_change_position_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='glycosite',
            old_name='Start',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='glycosite',
            old_name='Sequence',
            new_name='sequence',
        ),
        migrations.RemoveField(
            model_name='glycosite',
            name='Region',
        ),
        migrations.RemoveField(
            model_name='glycosite',
            name='Stop',
        ),
        migrations.AddField(
            model_name='glycosite',
            name='germline',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
    ]
