# Generated by Django 4.1.3 on 2023-08-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PinkStrawberry', '0067_rename_start_glycosite_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ms_peptide',
            name='sequence_start',
            field=models.IntegerField(null=True),
        ),
    ]
