# Generated by Django 4.1.3 on 2023-10-12 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PinkStrawberry', '0001_squashed_0069_glycosite_insequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='germline',
            name='IMGT_Gene_DB',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Germline', to='PinkStrawberry.imgt_gene_db'),
        ),
        migrations.AlterField(
            model_name='glycosite',
            name='germline',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='ms_peptide',
            name='sheet_sequence',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vquest_run',
            name='Project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='VQuest_Run', to='PinkStrawberry.project'),
        ),
    ]
